# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 09:23
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flflf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('profile', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preference', serialize=False, to='flflf.User')),
            ],
        ),
    ]
